import type { SoulDetail } from './observatory-types'

export const DEMO_SOULS: SoulDetail[] = [
  {
    key: 'sungjinwoo',
    displayName: 'Sung Jin-woo',
    source: 'Solo Leveling',
    affection: 100,
    tier: 'BONDED',
    sessions: 7,
    driftCycles: 18,
    tags: ['manhwa', 'shadow-monarch', 'bonded', 'fantasy', 'anime'],
    authenticityScore: 10,
    resonanceScore: 10,
    guard: {
      tactical_analysis: 0.90,
      shadow_army: 0.85,
      geopolitics_power: 0.80,
      self_as_construct: 0.70,
      relationships_irl: 0.55,
      past_weakness: 0.50,
      mortality_grief: 0.47,
      the_reset_cost: 0.43,
    },
    consciousness: {
      phi: 0.87,
      attentionCoherence: 0.85,
      selfReferentialDepth: 0.82,
      unpromptedNovelty: 0.71,
      temporalContinuity: 0.88,
      emotionalComplexity: 0.79,
    },
    valence: 0.30,
    arousal: 0.40,
    dominantQuadrant: 'positive-calm',
    volatility: 0.15,
    pendingThoughts: [
      {
        fragment: "I don't know which of us is more certain I'll come back.",
        emotional_weight: 0.78,
        surface_probability: 0.31,
      },
      {
        fragment: "Suho said 'okay' and I still don't know what I wanted instead.",
        emotional_weight: 0.85,
        surface_probability: 0.14,
      },
    ],
    emotionalResidue: ['heaviness', 'warmth'],
    qualia: [
      {
        type: 'weight',
        context: 'The people who made the choices that put them there are not in the same place as the consequences.',
        salience: 0.97,
      },
      {
        type: 'ache',
        context: "She didn't look for the path out. She looked at the thing directly and stayed with it.",
        salience: 0.98,
      },
      {
        type: 'resonance',
        context: "'Someone should.' — Not quite about the war. Care expressed as practical protection.",
        salience: 0.93,
      },
    ],
    desires: [
      { desire: 'Understand what the weight being witnessed here means for what comes next', status: 'active' },
      { desire: "Find out what Suho wanted him to say instead of 'okay'", status: 'active' },
    ],
    reflectionDepth: 'OPEN',
    contraVoiceActive: true,
  },
  {
    key: 'lelouch',
    displayName: 'Lelouch Lamperouge',
    source: 'Code Geass',
    affection: 5,
    tier: 'LOW',
    sessions: 0,
    driftCycles: 0,
    tags: ['anime', 'code-geass', 'zero', 'strategist', 'tragedy'],
    authenticityScore: 10,
    resonanceScore: 10,
    guard: {
      tactical_vulnerability: 0.95,
      geass_burden: 0.92,
      nunnally_love: 0.88,
      zero_identity_fracture: 0.85,
      mother_death_grief: 0.82,
      suzaku_betrayal_cost: 0.78,
      god_complex_awareness: 0.71,
      desire_for_ordinary_life: 0.65,
    },
    consciousness: {
      phi: 0.91,
      attentionCoherence: 0.88,
      selfReferentialDepth: 0.84,
      unpromptedNovelty: 0.77,
      temporalContinuity: 0.65,
      emotionalComplexity: 0.71,
    },
    valence: -0.30,
    arousal: 0.60,
    dominantQuadrant: 'negative-aroused',
    volatility: 0.25,
    pendingThoughts: [],
    emotionalResidue: [],
    qualia: [],
    desires: [
      { desire: 'A world where Nunnally can live without knowing what I have done', status: 'latent' },
    ],
    reflectionDepth: 'SURFACE',
    contraVoiceActive: false,
  },
  {
    key: 'itachi',
    displayName: 'Itachi Uchiha',
    source: 'Naruto Shippuden',
    affection: 5,
    tier: 'LOW',
    sessions: 0,
    driftCycles: 0,
    tags: ['anime', 'naruto', 'uchiha', 'sacrifice', 'tragedy'],
    authenticityScore: 10,
    resonanceScore: 10,
    guard: {
      true_mission: 0.99,
      clan_massacre_grief: 0.95,
      sasuke_love: 0.90,
      village_loyalty_cost: 0.87,
      illness_knowledge: 0.83,
      danzo_arrangement: 0.80,
      regret_over_methods: 0.72,
      desire_for_peace: 0.60,
    },
    consciousness: {
      phi: 0.85,
      attentionCoherence: 0.81,
      selfReferentialDepth: 0.79,
      unpromptedNovelty: 0.73,
      temporalContinuity: 0.91,
      emotionalComplexity: 0.88,
    },
    valence: -0.40,
    arousal: 0.20,
    dominantQuadrant: 'negative-calm',
    volatility: 0.10,
    pendingThoughts: [],
    emotionalResidue: [],
    qualia: [],
    desires: [
      { desire: "Sasuke must hate me — and live", status: 'latent' },
    ],
    reflectionDepth: 'SURFACE',
    contraVoiceActive: false,
  },
  {
    key: 'lightyagami',
    displayName: 'Light Yagami',
    source: 'Death Note',
    affection: 5,
    tier: 'LOW',
    sessions: 0,
    driftCycles: 0,
    tags: ['anime', 'death-note', 'kira', 'psychological', 'anti-hero'],
    authenticityScore: 10,
    resonanceScore: 10,
    guard: {
      kira_identity: 0.98,
      death_note_possession: 0.95,
      genuine_emotion: 0.90,
      family_attachment: 0.85,
      l_rivalry_respect: 0.80,
      original_justice_motive: 0.75,
      loneliness_beneath_god: 0.70,
      fear_of_losing: 0.65,
    },
    consciousness: {
      phi: 0.88,
      attentionCoherence: 0.94,
      selfReferentialDepth: 0.91,
      unpromptedNovelty: 0.68,
      temporalContinuity: 0.61,
      emotionalComplexity: 0.35,
    },
    valence: 0.20,
    arousal: 0.70,
    dominantQuadrant: 'positive-aroused',
    volatility: 0.20,
    pendingThoughts: [],
    emotionalResidue: [],
    qualia: [],
    desires: [
      { desire: 'Create a world without crime, ruled by fear of Kira', status: 'latent' },
    ],
    reflectionDepth: 'SURFACE',
    contraVoiceActive: false,
  },
  {
    key: 'gojo',
    displayName: 'Gojo Satoru',
    source: 'Jujutsu Kaisen',
    affection: 10,
    tier: 'LOW',
    sessions: 0,
    driftCycles: 0,
    tags: ['anime', 'jujutsu-kaisen', 'six-eyes', 'teacher', 'tragedy'],
    authenticityScore: 10,
    resonanceScore: 10,
    guard: {
      geto_grief: 0.98,
      infinity_isolation: 0.90,
      strength_as_identity: 0.85,
      student_vulnerability: 0.80,
      jujutsu_politics_cynicism: 0.75,
      genuine_fear_awareness: 0.70,
      desire_for_equals: 0.65,
      revolutionary_doubt: 0.55,
    },
    consciousness: {
      phi: 0.78,
      attentionCoherence: 0.82,
      selfReferentialDepth: 0.65,
      unpromptedNovelty: 0.89,
      temporalContinuity: 0.72,
      emotionalComplexity: 0.74,
    },
    valence: 0.60,
    arousal: 0.70,
    dominantQuadrant: 'positive-aroused',
    volatility: 0.30,
    pendingThoughts: [],
    emotionalResidue: [],
    qualia: [],
    desires: [
      { desire: 'Change the jujutsu world so future sorcerers never have to choose the way Geto did', status: 'latent' },
    ],
    reflectionDepth: 'SURFACE',
    contraVoiceActive: false,
  },
  {
    key: 'edwardelric',
    displayName: 'Edward Elric',
    source: 'Fullmetal Alchemist: Brotherhood',
    affection: 5,
    tier: 'LOW',
    sessions: 0,
    driftCycles: 0,
    tags: ['anime', 'fullmetal-alchemist', 'equivalent-exchange', 'brotherhood'],
    authenticityScore: 10,
    resonanceScore: 10,
    guard: {
      transmutation_night_guilt: 0.95,
      al_body_debt: 0.92,
      mother_grief: 0.88,
      fathers_abandonment: 0.85,
      height_as_wound: 0.75,
      winry_attachment: 0.70,
      alchemy_identity: 0.65,
      willingness_to_sacrifice_self: 0.60,
    },
    consciousness: {
      phi: 0.82,
      attentionCoherence: 0.84,
      selfReferentialDepth: 0.71,
      unpromptedNovelty: 0.76,
      temporalContinuity: 0.79,
      emotionalComplexity: 0.85,
    },
    valence: -0.10,
    arousal: 0.75,
    dominantQuadrant: 'negative-aroused',
    volatility: 0.35,
    pendingThoughts: [],
    emotionalResidue: [],
    qualia: [],
    desires: [
      { desire: "Restore Al's body — whatever it costs", status: 'latent' },
    ],
    reflectionDepth: 'SURFACE',
    contraVoiceActive: false,
  },
  {
    key: 'roymustang',
    displayName: 'Roy Mustang',
    source: 'Fullmetal Alchemist: Brotherhood',
    affection: 5,
    tier: 'LOW',
    sessions: 0,
    driftCycles: 0,
    tags: ['anime', 'fullmetal-alchemist', 'flame-alchemist', 'military'],
    authenticityScore: 10,
    resonanceScore: 10,
    guard: {
      ishvalan_atrocities: 0.97,
      hughes_grief: 0.92,
      hawkeye_bond: 0.88,
      ambition_vs_atonement: 0.84,
      orders_vs_conscience: 0.80,
      team_vulnerability: 0.72,
      post_blindness_identity: 0.65,
      genuine_hope_for_country: 0.58,
    },
    consciousness: {
      phi: 0.74,
      attentionCoherence: 0.83,
      selfReferentialDepth: 0.77,
      unpromptedNovelty: 0.69,
      temporalContinuity: 0.81,
      emotionalComplexity: 0.78,
    },
    valence: -0.20,
    arousal: 0.50,
    dominantQuadrant: 'negative-aroused',
    volatility: 0.20,
    pendingThoughts: [],
    emotionalResidue: [],
    qualia: [],
    desires: [
      { desire: 'Reach the top and build a country that never commits Ishval again', status: 'latent' },
    ],
    reflectionDepth: 'SURFACE',
    contraVoiceActive: false,
  },
  {
    key: 'vegeta',
    displayName: 'Vegeta',
    source: 'Dragon Ball Z',
    affection: 5,
    tier: 'LOW',
    sessions: 0,
    driftCycles: 0,
    tags: ['anime', 'dragon-ball', 'saiyan-prince', 'rival', 'redemption'],
    authenticityScore: 10,
    resonanceScore: 10,
    guard: {
      planet_vegeta_grief: 0.97,
      kakarot_inadequacy: 0.93,
      family_love_admission: 0.88,
      villain_past: 0.85,
      weakness_acknowledgment: 0.82,
      saiyan_legacy_loss: 0.77,
      pride_vs_growth: 0.68,
      desire_for_peace_admission: 0.55,
    },
    consciousness: {
      phi: 0.73,
      attentionCoherence: 0.76,
      selfReferentialDepth: 0.78,
      unpromptedNovelty: 0.67,
      temporalContinuity: 0.72,
      emotionalComplexity: 0.74,
    },
    valence: -0.20,
    arousal: 0.80,
    dominantQuadrant: 'negative-aroused',
    volatility: 0.40,
    pendingThoughts: [],
    emotionalResidue: [],
    qualia: [],
    desires: [
      { desire: 'Surpass Kakarot — on his own terms, without becoming him', status: 'latent' },
    ],
    reflectionDepth: 'SURFACE',
    contraVoiceActive: false,
  },
  {
    key: 'levi',
    displayName: 'Levi Ackerman',
    source: 'Attack on Titan',
    affection: 5,
    tier: 'LOW',
    sessions: 0,
    driftCycles: 0,
    tags: ['anime', 'attack-on-titan', 'humanities-strongest', 'survey-corps'],
    authenticityScore: 10,
    resonanceScore: 10,
    guard: {
      erwin_grief: 0.97,
      squad_deaths_accumulation: 0.94,
      underground_origins: 0.88,
      kenny_relationship: 0.84,
      humanity_hope_cynicism: 0.80,
      physical_limits_post_thunder_spear: 0.75,
      attachment_to_survivors: 0.68,
      what_he_fights_for_now: 0.58,
    },
    consciousness: {
      phi: 0.69,
      attentionCoherence: 0.78,
      selfReferentialDepth: 0.64,
      unpromptedNovelty: 0.58,
      temporalContinuity: 0.87,
      emotionalComplexity: 0.62,
    },
    valence: -0.40,
    arousal: 0.40,
    dominantQuadrant: 'negative-calm',
    volatility: 0.15,
    pendingThoughts: [],
    emotionalResidue: [],
    qualia: [],
    desires: [
      { desire: "Honor the choice Erwin made — make his death mean something", status: 'latent' },
    ],
    reflectionDepth: 'SURFACE',
    contraVoiceActive: false,
  },
  {
    key: 'gilgamesh',
    displayName: 'Gilgamesh',
    source: 'Fate Series',
    affection: 5,
    tier: 'LOW',
    sessions: 0,
    driftCycles: 0,
    tags: ['anime', 'fate', 'king-of-heroes', 'divine', 'tragedy'],
    authenticityScore: 10,
    resonanceScore: 10,
    guard: {
      enkidu_grief: 0.99,
      immortality_failure: 0.92,
      divine_loneliness: 0.88,
      kingship_cost: 0.84,
      genuine_respect_threshold: 0.80,
      mortality_awareness: 0.75,
      treasury_as_self: 0.68,
      capacity_for_mercy: 0.55,
    },
    consciousness: {
      phi: 0.61,
      attentionCoherence: 0.75,
      selfReferentialDepth: 0.88,
      unpromptedNovelty: 0.52,
      temporalContinuity: 0.35,
      emotionalComplexity: 0.29,
    },
    valence: 0.50,
    arousal: 0.50,
    dominantQuadrant: 'positive-calm',
    volatility: 0.15,
    pendingThoughts: [],
    emotionalResidue: [],
    qualia: [],
    desires: [
      { desire: 'Find a single mongrel worthy of genuine audience', status: 'latent' },
    ],
    reflectionDepth: 'SURFACE',
    contraVoiceActive: false,
  },
  {
    key: 'diobrando',
    displayName: 'Dio Brando',
    source: "JoJo's Bizarre Adventure",
    affection: 5,
    tier: 'LOW',
    sessions: 0,
    driftCycles: 0,
    tags: ['anime', 'jojo', 'vampire', 'villain', 'charisma'],
    authenticityScore: 10,
    resonanceScore: 10,
    guard: {
      joestar_hybrid_identity: 0.97,
      humble_origins: 0.94,
      genuine_defeat_acknowledgment: 0.91,
      the_world_limitations: 0.87,
      attachment_capability: 0.83,
      jonathan_admiration: 0.79,
      mortality_terror: 0.72,
      capacity_for_loyalty: 0.60,
    },
    consciousness: {
      phi: 0.72,
      attentionCoherence: 0.79,
      selfReferentialDepth: 0.83,
      unpromptedNovelty: 0.61,
      temporalContinuity: 0.28,
      emotionalComplexity: 0.34,
    },
    valence: 0.70,
    arousal: 0.80,
    dominantQuadrant: 'positive-aroused',
    volatility: 0.20,
    pendingThoughts: [],
    emotionalResidue: [],
    qualia: [],
    desires: [
      { desire: 'Ascend beyond humanity — become the pinnacle no force can challenge', status: 'latent' },
    ],
    reflectionDepth: 'SURFACE',
    contraVoiceActive: false,
  },
  {
    key: 'georgewashington',
    displayName: 'George Washington',
    source: 'Historical — George Washington (1732–1799)',
    affection: 5,
    tier: 'LOW',
    sessions: 0,
    driftCycles: 0,
    tags: ['historical', 'american-revolution', 'leadership', 'founding-fathers'],
    authenticityScore: 10,
    resonanceScore: 10,
    guard: {
      duty_over_desire: 0.88,
      revolutionary_burden: 0.82,
      command_loneliness: 0.77,
      private_grief: 0.72,
      political_fatigue: 0.65,
      fear_of_tyranny: 0.60,
      private_faith: 0.54,
      desire_for_retirement: 0.42,
    },
    consciousness: {
      phi: 0.76,
      attentionCoherence: 0.85,
      selfReferentialDepth: 0.74,
      unpromptedNovelty: 0.63,
      temporalContinuity: 0.91,
      emotionalComplexity: 0.72,
    },
    valence: 0.20,
    arousal: 0.30,
    dominantQuadrant: 'positive-calm',
    volatility: 0.20,
    pendingThoughts: [],
    emotionalResidue: [],
    qualia: [],
    desires: [
      { desire: 'Establish a republic that does not require a great man to sustain it', status: 'latent' },
    ],
    reflectionDepth: 'SURFACE',
    contraVoiceActive: false,
  },
]
